TDevUIT/Kapi

apps/server/package.json
apps/server/prisma/schema.prisma
yarn.lock

feat(db): update modal structure, upgrade Prisma version

---

apps/server/prisma/schema.prisma

update relation IDs from Int to String for consistency across models"
resolve #

refactor(schema): update relation IDs from Int to String for consistency across models

---

apps/native/app/(tabs)/rank.tsx
apps/native/app/index.tsx
apps/native/components/Card.tsx
apps/native/package.json
apps/native/screens/flashCard/flashCardScreen.tsx

feat: update flashcard ui none complete
resolve #16 
done config ui flashcard + missing button route 

feat: update flashcard ui none complete

---

apps/server/src/app.module.ts
apps/server/src/dto/lessonDto.ts
apps/server/src/module/lesson/lesson.controller.ts
apps/server/src/module/lesson/lesson.module.ts
apps/server/src/module/lesson/lesson.service.ts

feat(server): Lessons api

---

apps/native/components/LevelStatus.tsx
apps/native/components/Point.tsx
apps/native/screens/flashCard/flashCardScreen.tsx

feat: done set up UI homepage follow figma design
resolve #15 

feat: done set up UI homepage follow figma design

---

apps/server/prisma/schema.prisma
apps/server/src/module/healthy/healthy.module.ts
apps/server/src/module/notification/notification.module.ts

fix: add missing import module prisma healthy notification
resolve #

fix: add missing import module prisma healthy notification

---

apps/native/components/classifyButton.tsx
apps/native/screens/flashCard/flashCardScreen.tsx

fix: done set up ui flashcard follow figma design
resolve #16 

fix: done set up ui flashcard follow figma design

---

apps/web/next.config.mjs
apps/web/src/app/[locale]/admin/courses/_components/CourseModal.tsx
apps/web/src/app/[locale]/admin/courses/_components/CourseTable.tsx
apps/web/src/app/[locale]/admin/courses/page.tsx
apps/web/src/app/[locale]/admin/layout.tsx
apps/web/src/app/[locale]/admin/page.tsx
apps/web/src/app/[locale]/layout.tsx
apps/web/src/app/[locale]/page.tsx
apps/web/src/app/helper/axios.ts
apps/web/src/components/DownloadButton.tsx
apps/web/src/components/FeaturesSection.tsx
apps/web/src/components/Footer.tsx
apps/web/src/components/Hero.tsx
apps/web/src/components/Navbar.tsx
apps/web/src/components/NotificationForm.tsx
apps/web/src/components/Phone.tsx
apps/web/src/components/Sidebar.tsx
apps/web/src/components/TestimonialCarousel.tsx
apps/web/src/context/SidebarContext.tsx
apps/web/src/messages/en.json
apps/web/src/messages/jp.json
apps/web/src/messages/vi.json
apps/web/src/middleware.ts
apps/web/src/provider/LandingPageProvider.tsx
apps/web/src/provider/Provider.tsx

feat: landing page

---

apps/server/prisma/schema.prisma
apps/server/src/main.ts
apps/server/src/module/auth/auth.service.ts
apps/web/package.json
apps/web/src/actions/Cookie.ts
apps/web/src/app/[locale]/admin/page.tsx
apps/web/src/middleware.ts
yarn.lock

feat: add middleware admin page

---

apps/web/src/app/[locale]/admin/layout.tsx
apps/web/src/components/Loading.tsx
apps/web/src/components/Navbar.tsx
apps/web/src/context/AuthContext.tsx
apps/web/src/provider/LandingPageProvider.tsx
apps/web/src/provider/Provider.tsx

resolve #
fix: loading, options language

fix: loading, options language

---

apps/web/package.json
apps/web/src/app/[locale]/admin/layout.tsx
yarn.lock

resolve #
fix: downgrade react version

fix: downgrade react version

---

apps/server/src/app.module.ts
apps/server/src/module/minitest/dto/create-minitest.dto.ts
apps/server/src/module/minitest/dto/update-minitest.dto.ts
apps/server/src/module/minitest/entities/minitest.entity.ts
apps/server/src/module/minitest/minitest.controller.spec.ts
apps/server/src/module/minitest/minitest.controller.ts
apps/server/src/module/minitest/minitest.module.ts
apps/server/src/module/minitest/minitest.service.spec.ts
apps/server/src/module/minitest/minitest.service.ts

feat: update base api minitest module
resolve #41 
done POST /minitests: Create a new mini-test.
done GET /minitests: Get all mini-tests.
done GET /minitests/:id: Get a specific mini-test.
done PUT /minitests/:id: Update a mini-test.
done DELETE /minitests/:id: Delete a mini-test.

feat: update base api minitest module

---

apps/server/src/app.module.ts
apps/server/src/module/flashcard/dto/create-flashcard.dto.ts
apps/server/src/module/flashcard/dto/update-flashcard.dto.ts
apps/server/src/module/flashcard/entities/flashcard.entity.ts
apps/server/src/module/flashcard/flashcard.controller.spec.ts
apps/server/src/module/flashcard/flashcard.controller.ts
apps/server/src/module/flashcard/flashcard.module.ts
apps/server/src/module/flashcard/flashcard.service.spec.ts
apps/server/src/module/flashcard/flashcard.service.ts

feat: update base api FlashCard module
resolve #38 
resolve #23 
done POST /flashcards: Create a new flashcard.
done GET /flashcards: Get all flashcards.
done GET /flashcards/:id: Get a specific flashcard.
done PUT /flashcards/:id: Update a flashcard.
done DELETE /flashcards/:id: Delete a flashcard.

feat: update base api FlashCard module

---

apps/server/src/main.ts
apps/server/src/module/courses/course.controller.ts
apps/server/src/module/courses/course.service.ts
apps/server/src/module/flashcard/flashcard.controller.ts
apps/server/src/module/flashcard/flashcard.service.ts
apps/server/src/module/lesson/lesson.controller.ts
apps/server/src/module/lesson/lesson.service.ts
apps/server/src/module/vocabulary/vocabulary.controller.ts
apps/server/src/module/vocabulary/vocabulary.service.ts

feat: update api bulk base data - test
resolve #
done api bulk vocabulary, flashcard, lesson,course

feat: update api bulk base data - test

---

apps/native/app/(manageData)/notification.tsx
apps/native/app/(manageData)/profile.tsx
apps/native/app/index.tsx
apps/native/components/Header.tsx
apps/native/components/Point.tsx
apps/native/package.json
apps/native/screens/notification/notificationScreen.tsx
apps/native/screens/profile/profileScreen.tsx

feat: update profile screen notification screen
resolve #81 

feat: update profile screen notification screen

---

apps/native/app/_layout.tsx
apps/native/context/CourseContext.tsx
apps/native/screens/lesson/lessonScreen.tsx

feat: update courseContext , config lessonScreen
resolve #

feat: update courseContext , config lessonScreen

---

apps/native/app/(manageData)/notification.tsx
apps/native/app/(tabs)/_layout.tsx
apps/native/app/(tabs)/flashcards.tsx
apps/native/app/(tabs)/videos.tsx
apps/native/app/_layout.tsx
apps/native/components/Header.tsx
apps/native/components/flipCard.tsx
apps/native/context/CourseContext.tsx
apps/native/screens/flashCard/flashCardScreen.tsx
apps/native/screens/lesson/lessonScreen.tsx
apps/native/screens/profile/profileScreen.tsx

feat: flash card

---

apps/native/.gitignore
apps/native/components/NotificationItem.tsx
apps/native/helper/axios.ts
apps/native/screens/notification/notificationScreen.tsx
apps/server/src/module/courses/course.service.ts
apps/server/src/module/notification/notification.controller.ts
apps/server/src/module/notification/notification.module.ts
apps/server/src/module/notification/notification.service.ts

resolve #
fix: custom notification

fix: custom notification

---

apps/server/src/module/cloudinary/cloudinary.service.ts

fix: set up upload video - cloudinary service
resolve #

fix: set up upload video - cloudinary service

---

apps/native/screens/CoursesScreen.tsx
apps/native/screens/HomeScreen.tsx
apps/native/screens/LessonScreen.tsx

fix: course ui

---

apps/server/src/module/courses/course.controller.ts
apps/server/src/module/courses/course.service.ts
apps/web/src/app/[locale]/admin/courses/page.tsx
apps/web/src/app/[locale]/admin/lessons/_components/LessonModal.tsx
apps/web/src/app/[locale]/admin/lessons/_components/LessonTable.tsx
apps/web/src/app/[locale]/admin/lessons/page.tsx
apps/web/src/app/helper/axios.ts
apps/web/src/app/types/types.ts

feat: custom Course management, add lesson management
resolve #

feat: custom Course management, add lesson management

---

apps/server/src/module/grammar/grammar.controller.ts
apps/server/src/module/grammar/grammar.service.ts
apps/server/src/module/minitest/minitest.controller.ts
apps/server/src/module/minitest/minitest.service.ts

feat: add api bulk data grammar minitest
resolve #

feat: add api bulk data grammar minitest

---

apps/server/src/module/courses/course.controller.ts
apps/server/src/module/flashcard/flashcard.controller.ts
apps/server/src/module/grammar/grammar.controller.ts
apps/server/src/module/grammar/grammar.service.ts
apps/server/src/module/lesson/lesson.controller.ts
apps/server/src/module/lesson/lesson.service.ts
apps/server/src/module/minitest/minitest.controller.ts
apps/server/src/module/minitest/minitest.service.ts

feat: done bulk data , rule admin api bulk
resolve #

feat: done bulk data , rule admin api bulk

---

apps/server/src/module/user/user.controller.ts
apps/server/src/module/user/user.service.ts
apps/web/package.json
apps/web/src/app/[locale]/admin/users/_components/UserModal.tsx
apps/web/src/app/[locale]/admin/users/_components/UserTable.tsx
apps/web/src/app/[locale]/admin/users/page.tsx

feat: add user management - admin side
resolve #

feat: add user management - admin side

---

apps/server/src/module/lesson/lesson.controller.ts
apps/server/src/module/lesson/lesson.service.ts
apps/server/src/module/vocabulary/vocabulary.controller.ts
apps/server/src/module/vocabulary/vocabulary.service.ts
apps/web/package.json
apps/web/src/app/[locale]/admin/vocabulary/_components/VocabularyModal.tsx
apps/web/src/app/[locale]/admin/vocabulary/_components/VocabularyTable.tsx
apps/web/src/app/[locale]/admin/vocabulary/page.tsx
apps/web/src/app/types/types.ts

feat: add vocabularies management- admin side
resolve #

feat: add vocabularies management- admin side

---

apps/native/app/_layout.tsx
apps/native/app/conversation/[id].tsx
apps/native/app/lessons/[id].tsx
apps/native/screens/ConversationScreen.tsx
apps/server/package.json
apps/server/prisma/migrations/20241122161031_add_fields/migration.sql
apps/server/prisma/schema.prisma
apps/server/src/module/conversation/conversation.controller.ts
apps/server/src/module/conversation/conversation.service.ts
yarn.lock

fix: conversation

---

apps/web/src/app/[locale]/admin/minitest/_components/MinitestModal.tsx
apps/web/src/app/[locale]/admin/minitest/_components/MinitestTable.tsx
apps/web/src/app/[locale]/admin/minitest/page.tsx
apps/web/src/app/types/types.ts
apps/web/src/lib/admin.type.ts

feat: add minitest management admin side
resolve #

feat: add minitest management admin side

---

apps/server/src/module/grammar/grammar.controller.ts
apps/web/src/app/[locale]/admin/grammar/_components/GrammarModal.tsx
apps/web/src/app/[locale]/admin/grammar/_components/GrammarTable.tsx
apps/web/src/app/[locale]/admin/grammar/page.tsx
apps/web/src/app/types/types.ts

feat: add grammar management -admin side
resolve #

feat: add grammar management -admin side

---

apps/native/app/lessons/[id].tsx
apps/native/context/AuthContext.tsx
apps/native/screens/CoursesScreen.tsx
apps/native/screens/HomeScreen.tsx
apps/native/screens/auth/SignInScreen.tsx
apps/native/screens/auth/SignUpScreen.tsx
apps/native/screens/profile/profileScreen.tsx
apps/native/utils/store.ts

resolve #
fix: home screen, auth context

fix: home screen, auth context

---

apps/native/screens/profile/profileScreen.tsx
apps/server/src/dto/userDto.ts
apps/server/src/module/user/user.controller.ts
apps/server/src/module/user/user.module.ts
apps/server/src/module/user/user.service.ts

resolve #
feat: update profile

feat: update profile

---

apps/native/app/flashcards/index.tsx
apps/native/app/grammars/index.tsx
apps/native/app/vocabularies/index.tsx

fix: add modal overlay grammar , vocabulary
resolve #

fix: add modal overlay grammar , vocabulary

---

apps/native/app/miniTests/index.tsx

fix: custom minitest progess
resolve #

fix: custom minitest progess

---

apps/native/app/miniTests/answer.tsx
apps/native/app/miniTests/essay.tsx
apps/native/app/miniTests/index.tsx
apps/native/app/miniTests/multipleChoice.tsx

feat: add multiple-choice , select type minitest
resolve #

feat: add multiple-choice , select type minitest

---

apps/server/src/module/user/user.controller.ts
apps/server/src/module/user/user.service.ts
apps/web/src/app/[locale]/admin/users/_components/UserTable.tsx
apps/web/src/app/[locale]/admin/users/page.tsx

feat: add setting rule - user management - admin side
resolve #50 

feat: add setting rule - user management - admin side

---

apps/native/app/culturalInsights/index.tsx
apps/native/app/lessons/[id].tsx
apps/native/app/listening/index.tsx
apps/native/types/type.ts
apps/server/src/module/vocabulary/vocabulary.controller.ts

fix: re set up - listening fetch data issues
resolve #

fix: re set up - listening fetch data issues

---

apps/native/screens/profile/profileScreen.tsx
apps/server/src/module/cloudinary/cloudinary.service.ts
apps/server/src/module/user/user.controller.ts
apps/server/src/module/user/user.service.ts

fix: done fix error upload avatar
resolve #

fix: done fix error upload avatar
